version: 2.99.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - coverity_scan
  - gh_pages
skip_tags: true
image:
- Visual Studio 2015
configuration:
- Debug
- Release
platform:
- x64
- Win32
build_script:
- cmd: |
    cd /d %APPVEYOR_BUILD_FOLDER%/
    "%ProgramFiles(x86)%\MSBuild\14.0\Bin\amd64\MSBuild.exe" /verbosity:minimal  src/libEGL.vcxproj /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%"
    "%ProgramFiles(x86)%\MSBuild\14.0\Bin\amd64\MSBuild.exe" /verbosity:minimal  src/libGLESv2.vcxproj /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%"
    cd /d src/%CONFIGURATION%_%PLATFORM%/
    7z a %APPVEYOR_BUILD_FOLDER%/angle.zip *.dll *.pdb

artifacts:
  - path: angle.zip
    name: Angle
